name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
          python -m pip install pytest

      - name: Lint with ruff
        run: python -m ruff check src/uwscli tests

      - name: Compile sources
        run: python -m compileall src/uwscli

      - name: Run tests
        run: python -m pytest tests
